### ISSUE TITLE
[Suggestion] Formatting improvements for decimals

### ISSUE THREAD

**Issue by kohle** [PluginBugs/Issues-RPGMoney#10]
**Is your feature request related to a problem? Please describe.**
Money amounts that end in a 0 (such as `$0.10`) display as `$0.1`

![2021-09-01_19 09 38](https://user-images.githubusercontent.com/892288/131757069-5b207ade-1335-44ab-8031-c1d1350279a3.png)

**Describe the solution you'd like**
It should still display as `$0.10`, by adding the trailing 0

It would also be awesome if there was optional formatting for under 1.00 amounts, example converting `$0.15` to `15¢`

Absolutely love everything else so far :)

**Comment by kohle** [comment]
Looks like when you're dealing with small numbers it has the ability to show >2 decimals (how Java handles math?). It would be great if it could automatically round up to two decimal places!

![2021-09-03_20 26 34](https://user-images.githubusercontent.com/892288/132076377-220bc3c4-eab9-4ab5-90ed-2af474c9381f.png)

**Comment by LoneDev6** [comment]
Next update will fix these problems once for all:

![immagine](https://user-images.githubusercontent.com/27242001/134521692-376cce6c-de54-4c45-81db-381a00bfdb49.png)


![immagine](https://user-images.githubusercontent.com/27242001/134518604-94486f04-10f1-4056-a82d-8b8e1f9c0f1e.png)
![immagine](https://user-images.githubusercontent.com/27242001/134518637-cac8b74d-7cb8-4547-b5e0-7571d7e6fc02.png)
![immagine](https://user-images.githubusercontent.com/27242001/134518674-559ea682-e871-4132-afa8-91dd83500c30.png)
![immagine](https://user-images.githubusercontent.com/27242001/134518692-eed5b375-590a-473a-be7d-fce6d343b96a.png)

![immagine](https://user-images.githubusercontent.com/27242001/134518837-80963f95-62c0-4087-8d3c-d27bc6aa0190.png)
![immagine](https://user-images.githubusercontent.com/27242001/134518820-0533d238-5863-4d2e-bec4-ade26fa4841d.png)


![immagine](https://user-images.githubusercontent.com/27242001/134519881-e9443a39-9f1c-4a1c-9446-708fe145a1ab.png)

**Comment by LoneDev6** [comment]
About the `15¢` suggestion:  it's a good suggestion but I think this may confuse players and cents is not really used in games in general, I may add it in the future tho, feel free to open a new suggestion about it
