### ISSUE TITLE
[BUG] Legacy Material Support

### ISSUE THREAD

**Issue by kohle** [PluginBugs/Issues-RPGMoney#11]
**Describe the bug**
The first time a block in the config is broken (I am testing with wheat) after a server startup, there is a lag spike before the console puts out an error about legacy material support. No lag after this happens, just the first time one is broken.

`[[STDERR] ] org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!`

**To Reproduce**
1. Start server
2. Log in and break a crop block
3. Few seconds of lag
4. Then works as normal

**Expected behavior**
Not sure what would be causing this issue, something using an outdated method within the Bukkit API?

**Info (please complete the following information):**
 - Server version: git-Paper-243 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 20903fc)
 - Client version: Vanilla 1.17.1
 - Plugin version: 1.1.30

**Additional context**
Other installed plugins:
- EssentialsX 2.19.1-dev+4-fde6524
- LoneLibs 1.0.14
- Vault 1.7.3-b131

**Comment by LoneDev6** [comment]
Yep this is normal and you can ignore it, you see this message because of compatibility with < 1.13 servers
