### ISSUE TITLE
[BUG] Money drop only working in default worlds

### ISSUE THREAD

**Issue by StephenGFX** [PluginBugs/Issues-RPGMoney#15]
Greetings, I have small problem with the money drop in custom worlds. I did not disable them, but mobs do not drop any coins.
The feature only works in vanilla worlds, could please fix that ?

 - Server version: paper 1.17.1
 - Client version: Optifine 1.17.1
 - Plugin version: Latest

**Comment by LoneDev6** [comment]
You have to configure each world in the configuration file.
As you can see each world has its own list of entities and their money drop rate.
