### ISSUE TITLE
[Suggestion] BossMania Plugin Support

### ISSUE THREAD

**Issue by StephenGFX** [PluginBugs/Issues-RPGMoney#16]
Greetings,
We use a plugin that allows us to create custom mobs, however those mobs either don't drop money or you can't specify the amount of money they can drop.

Could you please add Bossmania support ? 
https://www.spigotmc.org/resources/bossmania-custom-mobs-creator-gui-based-frequently-updated-1-12-1-18-1.87464/

https://i.ibb.co/gMdr4WK/2021-12-18-13-57-47.png

**Comment by LoneDev6** [comment]
I don't own the plugin so I cannot add compatibility, please link this issue page to the plugin author so they might give me a license to use their plugin.
