### ISSUE TITLE
[Suggestion] Add option for silk touch money drops

### ISSUE THREAD

**Issue by kohle** [PluginBugs/Issues-RPGMoney#17]
**Is your feature request related to a problem? Please describe.**
Money does not drop from blocks when the player breaks it with a silk touch tool.

**Describe the solution you'd like**
Add an option for each block to enable silk touch, for example:

![image](https://user-images.githubusercontent.com/892288/149679993-56b26dfe-a8dd-4589-a276-0bfc6d31d8e0.png)

**Comment by kohle** [comment]
Any update on the possibility of adding this feature? Another option/suggestion is having either having a generic permission node like `rpgmoney.silktouch.all` or `rpgmoney.silktouch.MELON`

**Comment by LoneDev6** [comment]
Wouldn't that cause duplication issues?
