### ISSUE TITLE
[BUG] your RPGHuds addon + RPGMoney = BUG

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-RPGMoney#18]
https://www.spigotmc.org/resources/addon-rpghuds-for-itemsadder.97486/ + RPGMoney = 

since you have messages going through the actionbar, when I pick up money or lose it, my bar disappears for a while and appears again, if I put an update in rpghuds in ticks 1 or 0, it doesn't help, there is a visual bug when I get money, since HUD disappears for miles of a second and reappears, and I can't disable custom messages in Rpgmoney through the config, please add the function of disabling all rpgmoney messages through actionbar.

**Comment by LoneDev6** [comment]
Will be added `show_actionbar_messages`
