### ISSUE TITLE
[BUG] Bug con el plugin Reviveme (bug with Reviveme plugin)

### ISSUE THREAD

**Issue by chimal1994** [PluginBugs/Issues-RPGMoney#19]
using the other plugin's /reviveme command triggers the RPGmoney command

https://cdn.discordapp.com/attachments/814533381432803388/945701077154668614/Minecraft_1.18.1_-_Multijugador_servidor_de_terceros_22-02-2022_17-11-12.mp4

**Comment by LoneDev6** [comment]
I'll try to find a solution but seems the reviveme plugin is interfering with rpgmoney command because it has the same name.
