### ISSUE TITLE
Map names beginning with "world." do not drop money [BUG] 

### ISSUE THREAD

**Issue by ghost** [PluginBugs/Issues-RPGMoney#20]
I gather that the plugin has a problem reading the "." or I don't know the correct way to make it detect that character.

**Comment by LoneDev6** [comment]
Why are you creating worlds with special characters?
You should really use only A-z characters and _ in your file names.
It might also be a Spigot/Minecraft issue.

**Comment by ghost** [comment]
> 

It's really the only plugin that has given me that problem.
Anyway, it's been almost a year since that problem.
I managed to develop my own plugin that solved my needs. Thanks anyway.
