### ISSUE TITLE
More decimal length in money than drop. [Suggestion] 

### ISSUE THREAD

**Issue by ghost** [PluginBugs/Issues-RPGMoney#21]
Unfortunately, when you work with decimals below 0.01 the plugin rounds them to 0.
It would be interesting if it could work with decimals and be able to manipulate multipliers.

**Comment by ghost** [comment]
If you can't, it would be nice if everything below 0.01 is rounded up to 0.01.

**Comment by kohle** [comment]
Limiting the display to 2 decimal places was part of this bug: #10
