### ISSUE TITLE
The plugin is out of date [URGENT - Economic server]

### ISSUE THREAD

**Issue by Miluek** [PluginBugs/Issues-RPGMoney#23]
**Describe the bug**
The plugin will not load because it is out of date...

**To Reproduce**
1. Update to last PurpurMC build
2. Update ItemsAdder to last version
3. Update RPGbank to last version
4. Update Vault to last version
5. Update EssentialsX to last version
6. Update LoneLibs to last version

Server version: 
RPG money version: v1.1.32
RPG bank version: v1.0.15
ItemsAdder version: v3.1.1
LoneLibs version: v1.0.18
Vault version: v1.7.3
Essentials version: v2.19.4

**Expected behavior**
Plugin just not loading...

**Screenshots**
<img width="985" alt="Snimek_obrazovky_2022-04-17_v_3 15 05" src="https://user-images.githubusercontent.com/79774929/163837398-450362eb-53a6-4e79-a152-be016dd3d0ee.png">

**Info (please complete the following information):**
 - Server version: 1.18.2-R0.1-SNAPSHOT git-Purpur-1611 (MC: 1.18.2)
 - Client version: 1.18.2
 - Plugin version: lasted - v1.1.32

**Additional context**
Server log... (lasted)

[latest.log](https://github.com/PluginBugs/Issues-RPGMoney/files/8506763/latest.log)

**Comment by Miluek** [comment]
Can you help me please? I need to hurry up, I have Economic server... 🙂

**Comment by LoneDev6** [comment]
I suspect there is a plugin which has a command with the same name, this basically breaks RPGMoney commands registration.
Can you please check?
Thanks.

**Comment by Miluek** [comment]
Hello, okay, I will let you know in 3 hours... Thanks! 🙂

**Comment by Miluek** [comment]
Hello again! 🙂

I tried to execute commands from RPGmoney on the server to find out what other plugin uses the same commands and I didn't find anything, the server threw me an error that this command could not be executed, but this is because the RPGmoney plugin is not loaded, only chat whispers commands to me RPG money but the plugin does not work, it throws the error...

**Comment by Miluek** [comment]
What else can I try? @LoneDev6 🙂

**Comment by Miluek** [comment]
Any idea?

**Comment by Miluek** [comment]
@LoneDev6, I need help 🤣

**Comment by Miluek** [comment]
@LoneDev6? Can you help me please?

**Comment by Miluek** [comment]
I won't fix it without your help, I've been asking you for help for a week...

**Comment by Miluek** [comment]
... 🙁

**Comment by thefourcraft** [comment]
can you share all the config files for the plugins
RPG money and IA

**Comment by Miluek** [comment]
Sure, no problem...
In IA config I have disabled resource pack, because this is RealLife server, Lobby server have in IA config enabled the resource pack...

https://www.mediafire.com/file/jisdfdsc44a1q7g/Archiv.zip/file

There is last error info

<img width="876" alt="Snímek obrazovky 2022-05-02 v 10 39 20" src="https://user-images.githubusercontent.com/79774929/166207648-e8f8ff67-6ffa-45e7-98cc-3fbfbf145fbf.png">

**Comment by Miluek** [comment]
In the meantime, I tried:
- Remove MyCommands (Recommended by @thefourcraft on Discord)
- Remove PlugMan (Recommended by @thefourcraft on Discord)
- Remove WordGuard (Recommended by @thefourcraft on Discord)

However, all these steps have solved the problem, the problem persists.

**Comment by Miluek** [comment]
Solved! 🙂

**Comment by LoneDev6** [comment]
Which was the cause of the issue?

**Comment by Miluek** [comment]
The VentureChat plugin has the same /rm command to remove the message, RPGmoney has the same command, to solve the problem it is necessary to deactivate the /rm command in the VentureChat directory in the “commands” file...
![image](https://user-images.githubusercontent.com/79774929/166925259-f5e6a469-14f7-403d-a6a2-c1d69dd0fba5.png)
