### ISSUE TITLE
About admin money multiplier

### ISSUE THREAD

**Issue by qwe938775** [PluginBugs/Issues-RPGMoney#28]
Is it possible to turn off the currency multiplier of the administrator..
I don't know if there is a bug or other problems. When I cancel my own administrator, the money multiplier is normal. If it is set as an administrator, the money multiplier increases abnormally.

**Comment by LoneDev6** [comment]
https://rpgmoney.devs.beer/permissions#multiplier-drop

**Comment by qwe938775** [comment]
Admin Status - Currency Multiplier Abnormal..

**Comment by LoneDev6** [comment]
Did you remove the permission?
Negate the permission in your permissions manager.

`-rpgmoney.multiply.drop.*`

**Comment by qwe938775** [comment]
I think I know why when you are the admin he will use your preset 10x bonus to make the gold multiplier of the admin or admin so high, I just need to change the 10x back to 1x and it will work fine
