### ISSUE TITLE
Reload command not reloading everything

### ISSUE THREAD

**Issue by marlon233-omc** [PluginBugs/Issues-RPGMoney#29]
**Describe the bug**
the reload command only updates the multipliers and not the prices of the blocks and you have to be restarting the server to test if a configuration works well

**To Reproduce**
1. Modify the price of a block
2. run the reload command
3. test if the price was updated or not

**Expected behavior**
The plugin does not update block prices until the server is restarted.

**Info (please complete the following information):**
 - Server version: 1.19.2
 - Client version: 1.19.2
 - Plugin version: 1.1.32

**Comment by LoneDev6** [comment]
Will be fixed
