### ISSUE TITLE
[BUG] Zombie pickup money

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-RPGMoney#35]
**Describe the bug**
Zombies can pick up money

**To Reproduce**
1. Spawn money on zombie that can pickup
2. Zombie picks up money

**Expected behavior**
Money staying on the ground

**Screenshots**
![image](https://github.com/PluginBugs/Issues-RPGMoney/assets/16320315/edbdffb9-ac1c-4263-af09-44a502dc7ee5)

**Info (please complete the following information):**
 - Server version: 1.19.4 Spigot
 - Client version: 1.19.4 Fabric
 - Plugin version: 1.1.32-r2
 
 **Additional context**
 When the zombie dies, the money that the zombie picked up gets dropped on the ground and works properly but the amount of money isn't shown on the ground above the item

**Comment by LoneDev6** [comment]
I can add an option to allow zombies from picking up money and fix the missing display name on drop.

**Comment by yorik100** [comment]
> I can add an option to allow zombies from picking up money and fix the missing display name on drop.

As long as I can disable the option, to make it block them from picking it up
