### ISSUE TITLE
[BUG] Can't pick up money when inventory is full

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-RPGMoney#37]
**Describe the bug**
Can't pick up money if inventory is full

**To Reproduce**
1. Get full inventory
2. Try to pickup money
3. Doesn't work

**Expected behavior**
Being able to pick up money

**Info (please complete the following information):**
 - Server version: purpur 1.19.4
 - Plugin version: 1.1.32-r2

**Comment by LoneDev6** [comment]
It's sadly impossible to do that since Minecraft doesn't send any packet to the player if their inventory is full.
They can't simply pickup items so no event is triggered.

**Comment by yorik100** [comment]
> 

This issue doesn't happen with other money drop plugins that aren't supported by ItemsAdder, just make your own item pickup

**Comment by yorik100** [comment]
> It's sadly impossible to do that since Minecraft doesn't send any packet to the player if their inventory is full. They can't simply pickup items so no event is triggered.
