### ISSUE TITLE
[BUG] Unable to load normally in version 1.20.2. Please assist

### ISSUE THREAD

**Issue by qwe938775** [PluginBugs/Issues-RPGMoney#44]
- Server version: (Paper 1.20.2#293 / 300)
 - Client version: (normal version 1.20.2)

<img width="873" alt="image" src="https://github.com/PluginBugs/Issues-RPGMoney/assets/71574471/52d2b56b-acdb-4c3f-93a6-ed638c279cfb">

**Comment by LoneDev6** [comment]
Please post it as text, do not post errors as screenshots.
Thanks
