### ISSUE TITLE
[BUG] and [suggestions] Fixed head problem, it still won't give you money after picking and using

### ISSUE THREAD

**Issue by qwe938775** [PluginBugs/Issues-RPGMoney#5]
Fixed head problem, money will not increase after use

It is recommended to use other shortcut keys. Many RPGs use the F key, hold it in your hand, right click to configure as a good choice or customizable hotkey

**Comment by LoneDev6** [comment]
> 
> 
> Fixed head problem, money will not increase after use
> 
> It is recommended to use other shortcut keys. Many RPGs use the F key, hold it in your hand, right click to configure as a good choice or customizable hotkey

you can set this in config.yml
set press_f: true and right_click: false


let me know if it works for you :D

**Comment by qwe938775** [comment]
Thank you effectively, I found a mistake, if you use the item selected by F, the weapon will disappear,lol

Everything else is ok, thank you very much

**Comment by qwe938775** [comment]
Thank you effectively
