### ISSUE TITLE
[BUG] money drops from monsters from the spawner when they are turned off

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-RPGMoney#7]
money drops from monsters from the spawner when they are turned off

**Comment by MrJorman** [comment]
when 0% - ruby drop amount 0, but logically they should not fall out at all

**Comment by LoneDev6** [comment]
Sorry I don't understand this issue, be more specific and provide screenshots/video.
Also I need the server version and plugin version.
